# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 700))
        MainWindow.setMaximumSize(QtCore.QSize(800, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(10, 50, 181, 641))
        self.list.setObjectName("list")
        self.source_btn = QtWidgets.QPushButton(self.centralwidget)
        self.source_btn.setGeometry(QtCore.QRect(4, 2, 191, 41))
        self.source_btn.setObjectName("source_btn")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(200, 650, 111, 41))
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(320, 650, 111, 41))
        self.right_btn.setObjectName("right_btn")
        self.mirror_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mirror_btn.setGeometry(QtCore.QRect(440, 650, 111, 41))
        self.mirror_btn.setObjectName("mirror_btn")
        self.contr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.contr_btn.setGeometry(QtCore.QRect(560, 650, 111, 41))
        self.contr_btn.setObjectName("contr_btn")
        self.gray_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gray_btn.setGeometry(QtCore.QRect(680, 650, 111, 41))
        self.gray_btn.setObjectName("gray_btn")
        self.photo_lb = QtWidgets.QLabel(self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(206, 60, 581, 511))
        self.photo_lb.setText("")
        self.photo_lb.setObjectName("photo_lb")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.source_btn.clicked.connect(self.open_folder)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy Editor"))
        self.source_btn.setText(_translate("MainWindow", "Папка"))
        self.left_btn.setText(_translate("MainWindow", "Вліво"))
        self.right_btn.setText(_translate("MainWindow", "Вправо"))
        self.mirror_btn.setText(_translate("MainWindow", "Дзеркально"))
        self.contr_btn.setText(_translate("MainWindow", "Різкість"))
        self.gray_btn.setText(_translate("MainWindow", "Ч/Б"))

    def open_folder(self):
        workdir = QFileDialog.getExistingDirectory()

        filenames = os.listdir(workdir)
        images = []

        for file in filenames:
            if file.endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif', '.tiff', '.webp')):
                images.append(file)

        self.list.clear()
        self.list.addItems(images)


class ImageProccesor():

    def __init__(self, current_img, current_img_name, save_folder):
        self.current_img = current_img
        self.current_img_name = current_img_name
        self.save_folder = save_folder

    def load_img(self):

    
    def show_unedited(self):


    def gray(self):


    def save_img(self):

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
